### ISSUE TITLE
UCP: Redirect to dashboard for 2380 port

### ISSUE THREAD

**Issue by breeswish** [pingcap-incubator/tidb-dashboard#190]
## Description

When Dashboard is running in PD integration mode, it is running in 2379 port. However PD also serves 2380 port. When user access 2380 port, Dashboard is not accessable. We can redirect user to the correct port.

## Score

* 300

## Mentor(s)

* @HunDunDM 

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Golang

**Comment by disksing** [comment]
I think it is bad idea to do it. 2380 is for internal raft messages, not supposed to exposed to endpoint users.

**Comment by breeswish** [comment]
@disksing I agree. However it currently causes confusion for TiUP users and EdHuang want to see this feature 🤔

**Comment by disksing** [comment]
Can we use different color or special badge to clarify 2380 is only for internal use? Or maybe we can simply not display 2380, or give a direct link of TiDB Dashboard?
I think it is better to prevent users from making wrong operations, rather than trying to return some correct results when user does something wrong. The latter approach has no end: for example, users may want to use port 80...

/cc @c4pt0r
