### ISSUE TITLE
Standalone Dashboard on PD

### ISSUE THREAD

**Issue by breeswish** [pingcap-incubator/tidb-dashboard#22]
For easier deployment, we should update PD to support PD binary running Dashboard exclusively, i.e. only Dashboard functionality is provided and no PD functionality.

Discussion: Is it better to use standalone Dashboard binary instead of PD binary to fulfill this functionality?

**Comment by ericsyh** [comment]
If TiDB-Dashboard doesn't contain deployment/operation function in road-map, PD embedded will be more user-friendly since it has no effort to deploy/maintain. 
And for your case mentioned that only Dashboard functionality is update and no PD functionality, per my understanding, Dashboards' feature/bug fix will not be so urgent for users cause Dashboard doesn't impact their usage on TiDB.  They can wait the PD release to upgrade. 

But if TiDB-Dashboard wants to add deployment/operation function, it needs to be deploy separately like the Cloudera Manager/Apache Ambari.

**Comment by breeswish** [comment]
Agree with @ericsyh . We dont have many use cases for this. Close for now.
