### ISSUE TITLE
Show only selectable schemas and schema types

### ISSUE THREAD

**Issue by breeswish** [pingcap-incubator/tidb-dashboard#368]
## Feature Request

**Is your feature request related to a problem? Please describe:**

![image](https://user-images.githubusercontent.com/1916485/79640984-65865980-81c7-11ea-9a76-8ff83ea9aad2.png)

In statement overview page, it would be better to show only selectable schemas and schema types.

**Comment by baurine** [comment]
Yep, that's would be better, I thought that, but there is a problem, for example, when we select the statement type to "INSERT", the result will only contain "INSERT" type statements, and the statement types dropdown menu will also change to only have "INSERT" one option, right? the user has no chance to choose more than one statement type.

So the logic needs to change:

1. Get available schemas and statement types in local from statements result, instead of getting them from API.
1. After changing the schemas or statement types, the filter will only take action in the client side,  we don't need to pass these 2 parameters to the API anymore.

Do I understand this correctly?

**Comment by baurine** [comment]
As I explained above, close this issue. If we still need it, we can re-open it.
